<a href="https://colab.research.google.com/github/Thabby07/richter-predictor/blob/master/TFM_Entrenamiento_Modelo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
pip install mord
pip install sklearn-contrib-py-earth
pip install keras
pip install tensorflow==2.0.0-beta

     |████████████████████████████████| 1.0MB 2.6MB/s 
  Created wheel for sklearn-contrib-py-earth: filename=sklearn_contrib_py_earth-0.1.0-cp36-cp36m-linux_x86_64.whl size=3894254 sha256=c2ddaacf06f2911d1271bd08f6676ca6495e2316e68c9bc780b3bcbb2bbfc052
  Stored in directory: /root/.cache/pip/wheels/b7/8b/9c/4741513102ce3bd0f0227353dacdfbe9a5b0e47c261e45510b
Successfully built sklearn-contrib-py-earth


In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
from datetime import datetime
#from mord import LogisticAT
#from pyearth import Earth
from sklearn.model_selection import cross_val_score


In [0]:
train_values = pd.read_csv('/content/train_values.csv')
train_labels = pd.read_csv('/content/train_labels.csv')
test_values = pd.read_csv('/content/test_values.csv')

In [0]:
train = train_values.set_index('building_id').join(train_labels.set_index('building_id'), how='left')

In [6]:
train['damage_grade'].value_counts().sort_index(ascending=True)

1     25124
2    148259
3     87218
Name: damage_grade, dtype: int64

Por tanto, del dataset completo, el **grado 1** significa un **9.64%** del total, el **grado 2** un **56.89%** y el **grado 3** un **33.47%**.

In [7]:
# Now we exclude string categorical variables
#train = train.select_dtypes(exclude=['object'])
#test = test_values.select_dtypes(exclude=['object'])

# Or we can change string categorical to numeric categorical as dummies
train = pd.get_dummies(train)
test = pd.get_dummies(test_values)

train.head()

geo_level_1_id  ...  legal_ownership_status_w
building_id                  ...                          
802906                    6  ...                         0
28830                     8  ...                         0
94947                    21  ...                         0
590882                   22  ...                         0
201944                   11  ...                         0

[5 rows x 69 columns]

In [8]:
test = test.set_index('building_id')
test.head()

geo_level_1_id  ...  legal_ownership_status_w
building_id                  ...                          
300051                   17  ...                         0
99355                     6  ...                         0
890251                   22  ...                         0
745817                   26  ...                         0
421793                   17  ...                         0

[5 rows x 68 columns]

## Random Forest - sólo variables numéricas

In [0]:
damage_1 = train[train['damage_grade'] == 1].sample(n=25000)
damage_2 = train[train['damage_grade'] == 2].sample(n=25000)
damage_3 = train[train['damage_grade'] == 3].sample(n=25000)

In [0]:
train_sample = pd.concat([damage_1, damage_2, damage_3]).reset_index()
train_sample.head()

building_id  geo_level_1_id  ...  has_secondary_use_other  damage_grade
0       689827              13  ...                        0             1
1       780104              20  ...                        0             1
2       618103               8  ...                        0             1
3       333694              26  ...                        0             1
4       947549               5  ...                        0             1

[5 rows x 32 columns]

In [0]:
train.iloc[:, :-1] # all rows except target variable

geo_level_1_id  ...  legal_ownership_status_v
building_id                  ...                          
802906                    6  ...                         1
28830                     8  ...                         1
94947                    21  ...                         1
590882                   22  ...                         1
201944                   11  ...                         1
...                     ...  ...                       ...
688636                   25  ...                         1
669485                   17  ...                         1
602512                   17  ...                         1
151409                   26  ...                         1
747594                   21  ...                         1

[260601 rows x 68 columns]

In [0]:
test.columns.size

31

In [0]:
train = train_sample

In [0]:
#X = train.iloc[:, 0:38].values
#y = train.iloc[:, 38].values
X = train.iloc[:, 0:30].values
y = train.iloc[:, 30].values

In [0]:
# Partition train-test & scaler
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [0]:
RF_classifier = RandomForestClassifier(n_estimators=20, random_state=0)
RF_classifier.fit(train.iloc[:, :-1], train['damage_grade'])
RF_pred = RF_classifier.predict(test)

In [0]:
f1_micro_score = f1_score(y_test, RF_pred, average='macro')
print(f1_micro_score)

In [0]:
test.reset_index(level=0, inplace=True)

In [0]:
output = pd.DataFrame({'building_id': test['building_id'], 
                       'damage_grade': RF_pred})

timestamp = str(np.rint(datetime.timestamp(datetime.now())).astype(int))

path = "/content/" + timestamp + "_RF_competition_result.csv"
output.to_csv(path_or_buf=path, index=False)

## Ordinal predictor regressor (Logistic AT) - all variables + dummies

MORD: http://rikunert.com/ordinal_rating

In [0]:
LAT_classifier = LogisticAT(alpha=0) # alpha parameter set to zero to perform no regularisation

In [0]:
#cross_val_score(LAT_classifier, train.iloc[:, :-1], train['damage_grade'], cv=2, scoring='recall_micro')
#array([0.99998336, 0.99971965])

array([0.99998336, 0.99971965])

In [0]:
LAT_classifier.fit(train.iloc[:, :-1], train['damage_grade'])


In [0]:
LAT_pred = LAT_classifier.predict(test)


In [0]:
test.reset_index(level=0, inplace=True)


In [0]:
output = pd.DataFrame({'building_id': test['building_id'], 
                       'damage_grade': LAT_pred})

timestamp = str(np.rint(datetime.timestamp(datetime.now())).astype(int))

path = "/content/" + timestamp + "_LAT_competition_result.csv"
output.to_csv(path_or_buf=path, index=False)

## Mars - All variables + dummies

In [0]:
MARS_classifier = Earth()


In [0]:
MARS_classifier.fit(train.iloc[:, :-1], train['damage_grade'])


/usr/local/lib/python3.6/dist-packages/pyearth/earth.py:802: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  pruning_passer.run()
/usr/local/lib/python3.6/dist-packages/pyearth/earth.py:1055: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  coef, resid = np.linalg.lstsq(B, weighted_y[:, i])[0:2]


Earth(allow_linear=None, allow_missing=False, check_every=None,
      enable_pruning=True, endspan=None, endspan_alpha=None, fast_K=None,
      fast_h=None, feature_importance_type=None, max_degree=None,
      max_terms=None, min_search_points=None, minspan=None, minspan_alpha=None,
      penalty=None, smooth=None, thresh=None, use_fast=None, verbose=0,
      zero_tol=None)

In [0]:
print(MARS_classifier.trace())


Forward Pass
---------------------------------------------------------------
iter  parent  var  knot  mse       terms  gcv    rsq    grsq   
---------------------------------------------------------------
0     -       -    -     0.374314  1      0.374  0.000  0.000  
1     0       30   -1    0.000000  2      0.000  1.000  1.000  
---------------------------------------------------------------
Stopping Condition 1: Achieved RSQ value within threshold of 1

Pruning Pass
----------------------------------------------
iter  bf  terms  mse   gcv    rsq     grsq    
----------------------------------------------
0     -   2      0.00  0.000  1.000   1.000   
1     1   1      0.37  0.374  -0.000  -0.000  
----------------------------------------------
Selected iteration: 0



In [0]:
print(MARS_classifier.summary())

Earth Model
-------------------------------------
Basis Function  Pruned  Coefficient  
-------------------------------------
(Intercept)     No      8.89788e-16  
damage_grade    No      1            
-------------------------------------
MSE: 0.0000, GCV: 0.0000, RSQ: 1.0000, GRSQ: 1.0000


In [0]:
MARS_pred = MARS_classifier.predict(test)

In [0]:
test.reset_index(level=0, inplace=True)

In [0]:
output = pd.DataFrame({'building_id': test['building_id'], 
                       'damage_grade': MARS_pred})

timestamp = str(np.rint(datetime.timestamp(datetime.now())).astype(int))

path = "/content/" + timestamp + "_MARS_competition_result.csv"
output.to_csv(path_or_buf=path, index=False)

## GAM - Generalized Additive Models
https://codeburst.io/pygam-getting-started-with-generalized-additive-models-in-python-457df5b4705f

## Redes neuronales
### 1.- KERAS

In [0]:
# BORRAMOS EL REGISTRO CON BUILDING ID  811. AVERIGUAR POR QUE NO MAPEA
X = train.drop(['damage_grade'], axis=1).dropna()
y = train[['damage_grade']].dropna()

In [0]:
def get_f1(y_true, y_pred): #taken from old keras source code
    y_pred = tf.convert_to_tensor(y_pred, np.float32)
    y_true = tf.convert_to_tensor(y_true, np.float32)
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + K.epsilon())
    recall = true_positives / (possible_positives + K.epsilon())
    f1_val = 2*(precision*recall)/(precision+recall+K.epsilon())
    return f1_val

In [13]:
# first neural network with keras tutorial
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
import keras.backend as K

# define the keras model
model = Sequential()
model.add(Dense(12, input_dim=68, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=[get_f1])
# fit the keras model on the dataset
model.fit(X, y, epochs=5, batch_size=10)




Epoch 1/5





260601/260601 [==============================] - 33s 128us/step - loss: -15.5114 - get_f1: 0.9242
Epoch 2/5
260601/260601 [==============================] - 33s 126us/step - loss: -19.7410 - get_f1: 1.0000
Epoch 3/5
260601/260601 [==============================] - 33s 126us/step - loss: -19.7410 - get_f1: 1.0000
Epoch 4/5
260601/260601 [==============================] - 33s 127us/step - loss: -19.7410 - get_f1: 1.0000
Epoch 5/5
260601/260601 [==============================] - 33s 125us/step - loss: -19.7410 - get_f1: 1.0000


In [17]:
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

260601/260601 [==============================] - 5s 19us/step
Accuracy: 100.00


In [0]:
predicted = model.predict(test)

In [24]:
np.unique(predicted) # Wrong!!

array([1.], dtype=float32)

### 2.- Pytorch

Source: https://www.ethanrosenthal.com/2018/12/06/spacecutter-ordinal-regression/

In [0]:
#pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

import pandas as pd
import numpy as np
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import torch
from torch.utils.data import Dataset, DataLoader
import torch.optim as torch_optim
import torch.nn as nn
import torch.nn.functional as F
from torchvision import models
from datetime import datetime

In [52]:
train_values = pd.read_csv('/content/train_values.csv')
train_labels = pd.read_csv('/content/train_labels.csv')
test_values = pd.read_csv('/content/test_values.csv')
train = train_values.set_index('building_id').join(train_labels.set_index('building_id'), how='left')
train.head()

geo_level_1_id  ...  damage_grade
building_id                  ...              
802906                    6  ...             3
28830                     8  ...             2
94947                    21  ...             3
590882                   22  ...             2
201944                   11  ...             3

[5 rows x 39 columns]

Vamos a eliminar las **variables identificadores geográficas**.

In [55]:
X = train.drop(['damage_grade','geo_level_1_id','geo_level_2_id','geo_level_3_id'], axis=1).dropna()
y = train[['damage_grade']].drop(['geo_level_1_id','geo_level_2_id','geo_level_3_id'], axis=1).dropna()

KeyError: ignored

In [38]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.10, random_state=0)
X_train.head()

geo_level_1_id  ...  has_secondary_use_other
building_id                  ...                         
449186                    6  ...                        0
31725                    17  ...                        0
487608                   24  ...                        0
673184                   10  ...                        0
625777                   10  ...                        0

[5 rows x 38 columns]

In [39]:
Counter(train.damage_grade)

Counter({1: 25124, 2: 148259, 3: 87218})

In [40]:
#categorical embedding for columns having more than two values
embedded_cols = {n: len(col.cat.categories) for n,col in X.items() if len(col.cat.categories) > 2}
embedded_cols

AttributeError: ignored